services:
  documentation-app:
    build: ./apps/documentation-app
    ports:
      - 8000:3000
    environment:
      - EXTERNAL_URI=http://localhost:8000
  testing-app:
    build: ./apps/testing-app
    ports:
      - 8001:3000
    environment:
      - EXTERNAL_URI=http://localhost:8001
  validation-app:
    build: ./apps/validation-app
    ports:
      - 8002:3000
    environment:
      - EXTERNAL_URI=http://localhost:8002
  authorization-app:
    build: ./apps/authorization-app
    ports:
      - 8003:3000
    environment:
      - EXTERNAL_URI=http://localhost:8003
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 9094:9094 # Internal access
      - 9093:9093 # Controller communication
      - 9092:9092 # External access
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: kafka-docker-cluster-1
    healthcheck:
      test: /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9094 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  messaging-app:
    build: ./apps/messaging-app
    ports:
      - 8004:3000
    environment:
      - EXTERNAL_URI=http://localhost:8004
      - KAFKA_BROKERS=kafka:9094
    depends_on:
      - kafka
  user-api:
    build: ./apps/user-api
    ports:
      - 8005:3000
    environment:
      - EXTERNAL_URI=http://localhost:8005
      - KAFKA_BROKERS=kafka:9094
    depends_on:
      kafka:
        condition: service_healthy
  notification-app:
    build: ./apps/notification-app
    environment:
      - KAFKA_BROKERS=kafka:9094
    depends_on:
      kafka:
        condition: service_healthy
